version: '3.8'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ../
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URI=postgresql://myuser:mypassword@db/mydatabase
    depends_on :
      - db
    links:
      - db
  
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypasswor